# Generated by Django 4.0.5 on 2023-07-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField()),
                ('storage_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CloudUser',
            },
        ),
    ]
