# Generated by Django 4.0.5 on 2023-08-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('download_date', models.DateTimeField(null=True)),
                ('download_link', models.CharField(max_length=10)),
                ('storage_path', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cloud_models.clouduser')),
            ],
            options={
                'db_table': 'CloudFile',
            },
        ),
    ]
